### ISSUE TITLE
build apk failed

### ISSUE THREAD

**Issue by ZMNOTZ** [rhymelph/r_upgrade#16] opened 2020-07-05 13:04 UTC
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/emery/.pub-cache/hosted/pub.flutter-io.cn/r_upgrade-0.3.1/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'r_upgrade'.
> Project with path ':r_upgrade' could not be found in root project 'r_upgrade'.

**Comment by rhymelph** [comment] 2021-07-27 01:03
Duplicate of #40

**Closed** 2022-04-10 03:55 UTC
Labels: duplicate
